'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("default")>  _
        Public Property lastproject() As String
            Get
                Return CType(Me("lastproject"),String)
            End Get
            Set
                Me("lastproject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DEBUG() As Boolean
            Get
                Return CType(Me("DEBUG"),Boolean)
            End Get
            Set
                Me("DEBUG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("127.0.0.1")>  _
        Public Property DB_HOST() As String
            Get
                Return CType(Me("DB_HOST"),String)
            End Get
            Set
                Me("DB_HOST") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DB_NAME() As String
            Get
                Return CType(Me("DB_NAME"),String)
            End Get
            Set
                Me("DB_NAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DB_PREFIX() As String
            Get
                Return CType(Me("DB_PREFIX"),String)
            End Get
            Set
                Me("DB_PREFIX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
        Public Property DB_USER() As String
            Get
                Return CType(Me("DB_USER"),String)
            End Get
            Set
                Me("DB_USER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DB_PASS() As String
            Get
                Return CType(Me("DB_PASS"),String)
            End Get
            Set
                Me("DB_PASS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_UA_APP_KEY() As String
            Get
                Return CType(Me("PUSH_UA_APP_KEY"),String)
            End Get
            Set
                Me("PUSH_UA_APP_KEY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_UA_APP_SECRET() As String
            Get
                Return CType(Me("PUSH_UA_APP_SECRET"),String)
            End Get
            Set
                Me("PUSH_UA_APP_SECRET") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_UA_SOUND() As String
            Get
                Return CType(Me("PUSH_UA_SOUND"),String)
            End Get
            Set
                Me("PUSH_UA_SOUND") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PUSH_GCM_SANDBOX() As Boolean
            Get
                Return CType(Me("PUSH_GCM_SANDBOX"),Boolean)
            End Get
            Set
                Me("PUSH_GCM_SANDBOX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_GCM_KEY() As String
            Get
                Return CType(Me("PUSH_GCM_KEY"),String)
            End Get
            Set
                Me("PUSH_GCM_KEY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_GCM_SOUND() As String
            Get
                Return CType(Me("PUSH_GCM_SOUND"),String)
            End Get
            Set
                Me("PUSH_GCM_SOUND") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_GCM_KEY_LIVE() As String
            Get
                Return CType(Me("PUSH_GCM_KEY_LIVE"),String)
            End Get
            Set
                Me("PUSH_GCM_KEY_LIVE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_GCM_SOUND_LIVE() As String
            Get
                Return CType(Me("PUSH_GCM_SOUND_LIVE"),String)
            End Get
            Set
                Me("PUSH_GCM_SOUND_LIVE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PUSH_APNS_SANDBOX() As Boolean
            Get
                Return CType(Me("PUSH_APNS_SANDBOX"),Boolean)
            End Get
            Set
                Me("PUSH_APNS_SANDBOX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_APNS_CERTIFICATE() As String
            Get
                Return CType(Me("PUSH_APNS_CERTIFICATE"),String)
            End Get
            Set
                Me("PUSH_APNS_CERTIFICATE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_APNS_CERTIFICATE_PASSPHRASE() As String
            Get
                Return CType(Me("PUSH_APNS_CERTIFICATE_PASSPHRASE"),String)
            End Get
            Set
                Me("PUSH_APNS_CERTIFICATE_PASSPHRASE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_APNS_SOUND() As String
            Get
                Return CType(Me("PUSH_APNS_SOUND"),String)
            End Get
            Set
                Me("PUSH_APNS_SOUND") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_APNS_CERTIFICATE_LIVE() As String
            Get
                Return CType(Me("PUSH_APNS_CERTIFICATE_LIVE"),String)
            End Get
            Set
                Me("PUSH_APNS_CERTIFICATE_LIVE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_APNS_CERTIFICATE_PASSPHRASE_LIVE() As String
            Get
                Return CType(Me("PUSH_APNS_CERTIFICATE_PASSPHRASE_LIVE"),String)
            End Get
            Set
                Me("PUSH_APNS_CERTIFICATE_PASSPHRASE_LIVE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PUSH_APNS_SOUND_LIVE() As String
            Get
                Return CType(Me("PUSH_APNS_SOUND_LIVE"),String)
            End Get
            Set
                Me("PUSH_APNS_SOUND_LIVE") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.nuSOAP.My.MySettings
            Get
                Return Global.nuSOAP.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
